export interface Module {
  name: string
  tags: string[]
  isShowcase: boolean
}

export interface TierData {
  id: string
  name: string
  ages: string
  category: 'Foundation' | 'Robotics' | 'Creative' | 'Specialist'
  sessions: number
  duration: string
  hardware: string
  color: string
  modules: Module[]
}

export const CURRICULUM_DATA: TierData[] = [
  // ─── FOUNDATION ───────────────────────────────────────────────────────────
  {
    id: 'coding-explorers',
    name: 'Coding Explorers',
    ages: '4–6 yrs',
    category: 'Foundation',
    sessions: 16,
    duration: '1 hr',
    hardware: 'ZMROBO Alpha A (Stage 1 + 2)',
    color: '#117A65',
    modules: [
      { name: 'Introduction to Alpha A + MPU: What is a computer', tags: ['MPU', 'Cisco', 'Cambridge'], isShowcase: false },
      { name: 'Simple Machine — Spinning Top (Alpha A)', tags: [], isShowcase: false },
      { name: 'Simple Machine — Catapult (Alpha A)', tags: [], isShowcase: false },
      { name: 'MPU: Responsible screen use + devices', tags: ['MPU', 'Cisco'], isShowcase: false },
      { name: 'Simple Machine — Swing (Alpha A)', tags: [], isShowcase: false },
      { name: 'Simple Machine — Seesaw (Alpha A)', tags: [], isShowcase: false },
      { name: 'Simple Machine — Lawn Mower (Alpha A)', tags: [], isShowcase: false },
      { name: 'CodeMonkey Jr: Sequencing & Loops + Alpha A free build', tags: ['CM'], isShowcase: false },
      { name: 'Powered Machine — Gyrocar (Alpha A)', tags: [], isShowcase: false },
      { name: 'Powered Machine — Tricycle (Alpha A)', tags: [], isShowcase: false },
      { name: 'Powered Machine — Train Carriage (Alpha A)', tags: [], isShowcase: false },
      { name: 'CodeMonkey Jr: Advanced Sequencing + Alpha A build', tags: ['CM'], isShowcase: false },
      { name: 'Powered Machine — Jump Rope Robot (Alpha A)', tags: [], isShowcase: false },
      { name: 'Powered Machine — Intro to Motors (Alpha A)', tags: [], isShowcase: false },
      { name: 'CodeMonkey Jr: Conditional Loops + Alpha A build', tags: ['CM'], isShowcase: false },
      { name: 'Robot Story Showcase (Alpha A)', tags: [], isShowcase: true },
    ],
  },
  {
    id: 'junior-coders',
    name: 'Junior Coders',
    ages: '6–8 yrs',
    category: 'Foundation',
    sessions: 20,
    duration: '1 hr',
    hardware: 'ZMROBO Alpha A (Stage 2 + 3)',
    color: '#117A65',
    modules: [
      { name: 'Intro + MPU: Digital Citizenship + Online Safety', tags: ['MPU', 'Cisco', 'Cambridge'], isShowcase: false },
      { name: 'Powered Machine — Rowing Boat (Alpha A)', tags: [], isShowcase: false },
      { name: 'Powered Machine — Basketball Machine (Alpha A)', tags: [], isShowcase: false },
      { name: 'Coding A — Scratch Intro: events, sprites, animation', tags: [], isShowcase: false },
      { name: 'Dodo Math: Distances warm-up + Alpha A build', tags: ['CM'], isShowcase: false },
      { name: 'Coding B — Scratch Loops', tags: [], isShowcase: false },
      { name: 'Fundamental — Little Runner (Alpha A)', tags: [], isShowcase: false },
      { name: 'Beaver Achiever: Sequencing & Loops + Scratch Conditionals', tags: ['CM'], isShowcase: false },
      { name: 'Fundamental — Crab (Alpha A)', tags: [], isShowcase: false },
      { name: 'Fundamental — Hummingbird (Alpha A)', tags: [], isShowcase: false },
      { name: 'Beaver Achiever: Conditional Loops + MPU: What is AI', tags: ['CM', 'MPU'], isShowcase: false },
      { name: 'Fundamental — Little Dinosaur (Alpha A)', tags: [], isShowcase: false },
      { name: 'Coding C — Scratch Mini Project', tags: [], isShowcase: false },
      { name: 'Beaver Achiever: If/Else + Dodo Math: Angles', tags: ['CM'], isShowcase: false },
      { name: 'Google Sites A — first page, About Me', tags: [], isShowcase: false },
      { name: 'Fundamental — Bicycle (Alpha A)', tags: [], isShowcase: false },
      { name: 'Google Sites B — images, Hobbies, share link', tags: [], isShowcase: false },
      { name: 'Dodo Math: Multiplication warm-up + free code session', tags: ['CM'], isShowcase: false },
      { name: 'Sumo Ring Mission (Alpha A)', tags: [], isShowcase: false },
      { name: 'Robot Story + Google Sites Showcase', tags: [], isShowcase: true },
    ],
  },

  // ─── ROBOTICS — TRACK A ────────────────────────────────────────────────
  {
    id: 'robotics-junior',
    name: 'Robotics Junior',
    ages: '8–10 yrs',
    category: 'Robotics',
    sessions: 24,
    duration: '1.5 hrs',
    hardware: 'ZMROBO Alpha X (Stage 7)',
    color: '#1A5276',
    modules: [
      { name: "Let's Meet Alpha X — assembly, parts ID, controller setup", tags: [], isShowcase: false },
      { name: 'Rampaging Robot (Alpha X) — first movement, sequencing', tags: [], isShowcase: false },
      { name: 'Flashing Emoticons (Alpha X) — LED matrix, output control', tags: [], isShowcase: false },
      { name: 'MPU: Networks + Cybersecurity', tags: ['MPU', 'Cisco', 'Cambridge'], isShowcase: false },
      { name: 'Button Control (Alpha X) — input/output, conditionals intro', tags: [], isShowcase: false },
      { name: 'Magical Music (Alpha X) — buzzer, sound programming', tags: [], isShowcase: false },
      { name: 'Python Intro A via Replit + MPU: Algorithms', tags: ['MPU', 'Cambridge'], isShowcase: false },
      { name: 'Stop Timely (Alpha X) — timer functions, precise control', tags: [], isShowcase: false },
      { name: 'Rescue Lights (Alpha X) — sensors, conditional response', tags: [], isShowcase: false },
      { name: 'Python Intro B — loops, conditionals, functions', tags: [], isShowcase: false },
      { name: 'Return Automatically (Alpha X) — obstacle detection', tags: [], isShowcase: false },
      { name: 'Obstacle Avoidance (Alpha X) — multi-sensor autonomy', tags: [], isShowcase: false },
      { name: 'AI — Teachable Machine A: train image classifier', tags: ['CM'], isShowcase: false },
      { name: 'Line Follower Robot (Alpha X) — colour sensor', tags: [], isShowcase: false },
      { name: 'Python + Robot Control — connect Python to Alpha X', tags: [], isShowcase: false },
      { name: 'Reaction Game (Alpha X) — real-time input, game logic', tags: [], isShowcase: false },
      { name: 'AI — Teachable Machine B: sound classifier', tags: [], isShowcase: false },
      { name: 'Colourful Racing Car (Alpha X) — colour sensor + speed', tags: [], isShowcase: false },
      { name: 'Capstone Planning — design obstacle track, pseudocode', tags: [], isShowcase: false },
      { name: 'Capstone Build A (Alpha X)', tags: [], isShowcase: false },
      { name: 'Capstone Build B (Alpha X)', tags: [], isShowcase: false },
      { name: 'Capstone Build C (Alpha X) — final refinements', tags: [], isShowcase: false },
      { name: 'Exam + Portfolio Review', tags: [], isShowcase: false },
      { name: 'Obstacle Course Showcase (Alpha X)', tags: [], isShowcase: true },
    ],
  },
  {
    id: 'robotics-advanced',
    name: 'Robotics Advanced',
    ages: '10–12 yrs',
    category: 'Robotics',
    sessions: 24,
    duration: '1.5 hrs',
    hardware: 'ZMROBO Innovation Storm 2108E',
    color: '#1A5276',
    modules: [
      { name: 'Innovation Storm — Intro + Build A', tags: [], isShowcase: false },
      { name: 'Innovation Storm — Build B + First Program', tags: [], isShowcase: false },
      { name: 'MPU: AI Ethics + Data Privacy', tags: ['MPU', 'Cisco', 'Cambridge'], isShowcase: false },
      { name: 'Sensor Calibration + Motor Control (Innovation Storm)', tags: [], isShowcase: false },
      { name: 'Python on Innovation Storm A — variables, loops, sensor data', tags: [], isShowcase: false },
      { name: 'Python on Innovation Storm B — functions, sensor-triggered code', tags: [], isShowcase: false },
      { name: 'MIT Day of AI — Session A', tags: ['MIT'], isShowcase: false },
      { name: 'AI Vision — Face Detection (Innovation Storm)', tags: [], isShowcase: false },
      { name: 'AI Vision — Gesture Recognition (Innovation Storm)', tags: [], isShowcase: false },
      { name: 'MIT Day of AI — Session B', tags: ['MIT'], isShowcase: false },
      { name: 'AI Vision — Object Recognition (Innovation Storm)', tags: [], isShowcase: false },
      { name: 'AI Vision — QR Code + Navigation (Innovation Storm)', tags: [], isShowcase: false },
      { name: 'IBM SkillsBuild — Session A: AI fundamentals', tags: ['IBM'], isShowcase: false },
      { name: 'MPU: IoT + Future of Computing', tags: ['MPU', 'Cisco'], isShowcase: false },
      { name: 'IBM SkillsBuild — Session B: Cybersecurity', tags: ['IBM'], isShowcase: false },
      { name: 'Shared: Python AI Intro A', tags: ['Shared'], isShowcase: false },
      { name: 'Shared: Web App A — HTML/CSS', tags: ['Shared'], isShowcase: false },
      { name: 'Shared: Web App B — Flask basics', tags: ['Shared'], isShowcase: false },
      { name: 'Capstone Choice + Planning (AI Security Bot / Smart Traffic / Gesture Robot)', tags: [], isShowcase: false },
      { name: 'Capstone Build A (Innovation Storm)', tags: [], isShowcase: false },
      { name: 'Capstone Build B (Innovation Storm)', tags: [], isShowcase: false },
      { name: 'Capstone Build C (Innovation Storm)', tags: [], isShowcase: false },
      { name: 'Capstone Build D + Presentation Prep', tags: [], isShowcase: false },
      { name: 'AI Robot Capstone Demo (Innovation Storm)', tags: [], isShowcase: true },
    ],
  },

  // ─── CREATIVE — TRACK B ────────────────────────────────────────────────
  {
    id: 'creative-junior',
    name: 'Creative Junior',
    ages: '8–10 yrs',
    category: 'Creative',
    sessions: 20,
    duration: '1 hr',
    hardware: 'Laptop only · Roblox Studio',
    color: '#6C3483',
    modules: [
      { name: 'Intro + MPU: Digital Creativity + Copyright', tags: ['MPU', 'Cisco'], isShowcase: false },
      { name: 'Roblox Studio — Interface: toolbox, workspace, parts', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Building Basics A: place, resize, colour', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Building Basics B: terrain, environment', tags: [], isShowcase: false },
      { name: 'Game Logic Inspiration', tags: ['CM'], isShowcase: false },
      { name: 'Roblox Studio — Obby Design A: killbricks, checkpoints', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Obby Design B: obstacles, test, iterate', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Obby Design C: polish, theme, music', tags: [], isShowcase: false },
      { name: 'Scratch — Creative Project', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Lua Intro A: variables, print hello world', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Lua Intro B: onTouched events', tags: [], isShowcase: false },
      { name: 'MPU: AI in Creative Industries', tags: ['MPU', 'Cisco'], isShowcase: false },
      { name: 'Roblox Studio — Lua Conditionals: if/then/else', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Map Build A: choose theme, plan layout', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Map Build B: add Lua interactions', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Map Build C: peer playtest + feedback', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Map Build D: final polish, publish', tags: [], isShowcase: false },
      { name: 'Scratch + CodeMonkey Wrap-up', tags: ['CM'], isShowcase: false },
      { name: 'Showcase Prep — rehearsal, portfolio screenshots', tags: [], isShowcase: false },
      { name: 'Obby + Map Showcase (Roblox Studio)', tags: [], isShowcase: true },
    ],
  },
  {
    id: 'creative-advanced',
    name: 'Creative Advanced',
    ages: '10–12 yrs',
    category: 'Creative',
    sessions: 24,
    duration: '1 hr',
    hardware: 'Laptop only · Roblox Studio + Figma + AI',
    color: '#6C3483',
    modules: [
      { name: 'Intro + MPU: Generative AI Ethics + Digital IP', tags: ['MPU', 'Cisco', 'Cambridge'], isShowcase: false },
      { name: 'Roblox Studio — Lua Advanced A: OOP, modules, RemoteEvents', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Lua Advanced B: DataStores, leaderboards', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Game Systems A: health, damage, respawn', tags: [], isShowcase: false },
      { name: 'Roblox Studio — Game Systems B: inventory, currency, shop UI', tags: [], isShowcase: false },
      { name: 'Figma — UI/UX Intro: frames, components, game UI wireframe', tags: [], isShowcase: false },
      { name: 'Figma — UI/UX Design: health bar, inventory, export to Roblox', tags: [], isShowcase: false },
      { name: 'Prompt Engineering A — how LLMs work, ChatGPT + Claude', tags: [], isShowcase: false },
      { name: 'Prompt Engineering B — use AI to write Roblox Lua', tags: [], isShowcase: false },
      { name: 'Midjourney — AI Art A: text-to-image, prompt crafting', tags: [], isShowcase: false },
      { name: 'Midjourney — AI Art B: concept art, import to Roblox', tags: [], isShowcase: false },
      { name: 'Hugging Face — AI Models: text + image for creative use', tags: [], isShowcase: false },
      { name: 'MPU: Online Identity + IP', tags: ['MPU', 'Cambridge'], isShowcase: false },
      { name: 'Shared: Python AI Intro', tags: ['Shared'], isShowcase: false },
      { name: 'Shared: Web App — creative portfolio page', tags: ['Shared'], isShowcase: false },
      { name: 'Capstone — Agency Brief + Planning', tags: [], isShowcase: false },
      { name: 'Capstone — Roblox World A: terrain, structures, theme', tags: [], isShowcase: false },
      { name: 'Capstone — Roblox World B: Lua interactions, game systems', tags: [], isShowcase: false },
      { name: 'Capstone — AI Assets + Figma: generate art, UI mockup', tags: [], isShowcase: false },
      { name: 'Capstone — Pitch Prep A: agency deck, rehearse', tags: [], isShowcase: false },
      { name: 'Capstone — Pitch Prep B: final polish', tags: [], isShowcase: false },
      { name: 'Portfolio Assembly', tags: [], isShowcase: false },
      { name: 'Exam + Review', tags: [], isShowcase: false },
      { name: 'Creative Tech Agency Showcase', tags: [], isShowcase: true },
    ],
  },

  // ─── SPECIALIST — TRACK C ──────────────────────────────────────────────
  {
    id: 'specialist-junior',
    name: 'Specialist Junior',
    ages: '8–10 yrs',
    category: 'Specialist',
    sessions: 20,
    duration: '1 hr',
    hardware: 'Laptop only · Python',
    color: '#1E8449',
    modules: [
      { name: 'Intro + MPU: CS Concepts + Algorithms', tags: ['MPU', 'Cambridge'], isShowcase: false },
      { name: 'Python A — Variables, data types, print, input', tags: [], isShowcase: false },
      { name: 'CodeMonkey — Coding Adventure Part I: Fundamentals', tags: ['CM'], isShowcase: false },
      { name: 'Python B — Conditions: if/elif/else', tags: [], isShowcase: false },
      { name: 'Dodo Math: Distances warm-up + Python practice', tags: ['CM'], isShowcase: false },
      { name: 'Python C — Loops: for, while, range', tags: [], isShowcase: false },
      { name: 'CodeMonkey — Coding Adventure Part II: Functions & Conditions', tags: ['CM'], isShowcase: false },
      { name: 'Python D — Functions: define, parameters, return', tags: [], isShowcase: false },
      { name: 'MPU: Algorithms + Computational Thinking', tags: ['MPU', 'Cambridge'], isShowcase: false },
      { name: 'Python E — Lists + Strings', tags: [], isShowcase: false },
      { name: 'CodeMonkey — Coding Adventure Part III: Logic & Events', tags: ['CM'], isShowcase: false },
      { name: 'Dodo Math: Angles warm-up + Python mini project', tags: ['CM'], isShowcase: false },
      { name: 'Skill Mode Part I + Python debugging', tags: ['CM'], isShowcase: false },
      { name: 'HTML/CSS A — Structure: tags, elements, basic page', tags: [], isShowcase: false },
      { name: 'HTML/CSS B — Styling: colours, fonts, layout', tags: [], isShowcase: false },
      { name: 'Skill Mode Part II + continue HTML/CSS', tags: ['CM'], isShowcase: false },
      { name: 'Calculator Project A — plan, build basic calculator', tags: [], isShowcase: false },
      { name: 'Calculator Project B — functions, error handling, polish', tags: [], isShowcase: false },
      { name: 'Presentation Prep — rehearse 3-minute code walkthrough', tags: [], isShowcase: false },
      { name: 'Calculator Showcase + Exam', tags: [], isShowcase: true },
    ],
  },
  {
    id: 'specialist-advanced',
    name: 'Specialist Advanced',
    ages: '10–12 yrs',
    category: 'Specialist',
    sessions: 24,
    duration: '1 hr',
    hardware: 'Laptop only · Python + AI + Web',
    color: '#1E8449',
    modules: [
      { name: 'Intro + MPU: Data + Networks + Security', tags: ['MPU', 'Cisco', 'Cambridge'], isShowcase: false },
      { name: 'Python OOP A — Classes, objects, __init__, methods', tags: [], isShowcase: false },
      { name: 'Python OOP B — Inheritance, encapsulation', tags: [], isShowcase: false },
      { name: 'MPU: Algorithms + AI Concepts', tags: ['MPU', 'Cambridge', 'Cisco'], isShowcase: false },
      { name: 'pandas A — DataFrames, read CSV, basic exploration', tags: [], isShowcase: false },
      { name: 'pandas B — Filtering, groupby, stats, matplotlib', tags: [], isShowcase: false },
      { name: 'scikit-learn A — What is classification, first model', tags: [], isShowcase: false },
      { name: 'scikit-learn B — Train model, accuracy, predictions', tags: [], isShowcase: false },
      { name: 'Streamlit — deploy pandas/scikit-learn as Python web app', tags: [], isShowcase: false },
      { name: 'Hugging Face A — pre-trained models, text model via API', tags: [], isShowcase: false },
      { name: 'Hugging Face B + MPU: Ethics of Data', tags: ['MPU', 'Cisco'], isShowcase: false },
      { name: 'Web Dev A — HTML/CSS review, responsive basics', tags: [], isShowcase: false },
      { name: 'Web Dev B — JavaScript basics, DOM, click events', tags: [], isShowcase: false },
      { name: 'Web Dev C — JS + Python bridge, fetch request', tags: [], isShowcase: false },
      { name: 'Flask A — routes, templates, first Flask app', tags: [], isShowcase: false },
      { name: 'Flask B — forms, data, Python processes result', tags: [], isShowcase: false },
      { name: 'Shared: Python AI + Flask integration', tags: ['Shared'], isShowcase: false },
      { name: 'Capstone Planning — wireframe, plan AI feature', tags: [], isShowcase: false },
      { name: 'Capstone Build A — HTML/CSS + Flask routes', tags: [], isShowcase: false },
      { name: 'Capstone Build B — AI feature (pandas or scikit-learn)', tags: [], isShowcase: false },
      { name: 'Capstone Build C — JavaScript interactivity, polish', tags: [], isShowcase: false },
      { name: 'Capstone Build D — Streamlit AI demo, code walkthrough prep', tags: [], isShowcase: false },
      { name: 'Exam + Portfolio', tags: [], isShowcase: false },
      { name: 'Full Web App Showcase', tags: [], isShowcase: true },
    ],
  },
]

export interface TrialTimeBlock {
  time: string
  label: string
}

export const TRIAL_CLASS = {
  title: 'Trial Class',
  ages: 'All ages 4–12',
  duration: '1 hour',
  hardware: 'ZMROBO Alpha A + CodeMonkey + Laptop basics',
  timeBlocks: [
    { time: '0–10 min', label: 'Welcome + Programme Introduction — show Alpha A kit, explain programme pathway' },
    { time: '10–15 min', label: 'Laptop Basics — screen, keyboard, trackpad, USB ports, browser navigation' },
    { time: '15–40 min', label: 'Alpha A Build — Spinning Top (ages 4–8) OR Catapult (ages 8–12)' },
    { time: '40–55 min', label: 'CodeMonkey — Jr: Sequencing & Loops (ages 4–8) OR Coding Adventure I (ages 8–12)' },
    { time: '55–60 min', label: 'Parent Showcase + programme info + enrollment discussion' },
  ],
  note: "Use teacher's CodeMonkey login — no student account needed. Robot must physically work by end.",
}

export const TAG_STYLES: Record<string, { text: string; bg: string }> = {
  MPU: { text: '#1A6FA8', bg: '#E8F4FD' },
  CM: { text: '#E65100', bg: '#FFF3E0' },
  Cisco: { text: '#0D47A1', bg: '#E3F2FD' },
  Cambridge: { text: '#283593', bg: '#E8EAF6' },
  Shared: { text: '#6A1B9A', bg: '#F3E5F5' },
  MIT: { text: '#880E4F', bg: '#FCE4EC' },
  IBM: { text: '#1565C0', bg: '#E8EAF6' },
}

export const SHARED_MODULE = {
  title: 'Python Introduction to AI + Web App Engineering',
  description:
    'Woven into all three advanced branch sessions. Not a separate class. Topics: Python AI basics · HTML · CSS · Flask · deploy a simple web app. Every advanced student deploys one working web app by end of year regardless of track.',
  sessions: [
    'Robotics Advanced: sessions 16–18',
    'Creative Advanced: sessions 14–15',
    'Specialist Advanced: session 17',
  ],
}
