export const CURRICULUM: Record<string, string[]> = {
  'Coding Explorers': [
    'Introduction + Digital Literacy',
    'Physical Computing A — Matatalab',
    'Unplugged Activities',
    'Physical Computing B — Matatalab',
    'Creative Coding A — CodeMonkey Jr',
    'Creative Coding B — CodeMonkey Jr',
    'Review + Showcase',
  ],
  'Junior Coders': [
    'Introduction + Digital Literacy',
    'Coding A — Scratch',
    'Robotics A — Alpha A',
    'AI Theory',
    'Coding B — CodeMonkey',
    'Robotics B — Alpha A',
    'Web — Google Sites',
    'Review + Showcase',
  ],
  'Robotics Junior': [
    'Introduction + Digital Literacy',
    'Robotics A — Alpha X',
    'Python Intro',
    'AI — Teachable Machine',
    'Robotics B — Alpha X Advanced',
    'Review + Showcase',
  ],
  'Robotics Advanced': [
    'Introduction + Digital Literacy',
    'Intelligence Storm Build',
    'Python + C Programming',
    'AI Vision Module',
    'Capstone + Showcase',
  ],
  'Creative Junior': [
    'Intro to Creative Coding',
    'Scratch Advanced',
    'Roblox Studio — Lua Intro',
    'CoSpaces Edu VR',
    'Showcase + Portfolio',
  ],
  'Creative Advanced': [
    'Roblox Studio — Lua Advanced',
    'CoSpaces Advanced',
    'Figma UI/UX Design',
    'Prompt Engineering',
    'Generative AI — Midjourney + Hugging Face',
    'Creative Capstone',
  ],
  'Specialist Junior': [
    'Introduction + CS Concepts',
    'Python Fundamentals A',
    'Python Fundamentals B',
    'Web Basics — HTML/CSS',
    'Logic + Problem Solving',
    'Review + Showcase',
  ],
  'Specialist Advanced': [
    'Python Advanced',
    'Data + pandas',
    'ML with ml5.js',
    'scikit-learn',
    'Hugging Face',
    'Web Dev — JS + Flask',
    'MIT Day of AI',
    'IBM SkillsBuild',
    'Capstone Project',
  ],
}